//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontierVOps.ChannelMapWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIOSApp_DC_TestEntities : DbContext
    {
        public FIOSApp_DC_TestEntities()
            : base("name=FIOSApp_DC_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tFIOSBitMap> tFIOSBitMaps { get; set; }
        public DbSet<tFiosBitmapStationMap> tFiosBitmapStationMaps { get; set; }
        public DbSet<tFIOSBitmapVersion> tFIOSBitmapVersions { get; set; }
        public DbSet<tFIOSLineup> tFIOSLineups { get; set; }
        public DbSet<tFIOSRegion> tFIOSRegions { get; set; }
        public DbSet<tFIOSStation> tFIOSStations { get; set; }
    }
}
