//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontierVOps.ChannelMapWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFIOSRegion
    {
        public string strFIOSRegionId { get; set; }
        public string strFIOSRegionName { get; set; }
        public string strVHOId { get; set; }
        public string strCommunityId { get; set; }
        public string strStateCountyId { get; set; }
        public string strZipCode { get; set; }
        public string strDMAId { get; set; }
        public string strLocationId { get; set; }
        public string strTimeZoneId { get; set; }
        public string strVirtualChannelPosition { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public Nullable<System.DateTime> dtLastUpdateDate { get; set; }
        public string strNeedsDSTCorrection { get; set; }
    }
}
