//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontierVOps.ChannelMapWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFIOSBitmapVersion
    {
        public int intBitMapId { get; set; }
        public string strBitMapMD5Digest { get; set; }
        public string strFIOSVersionAliasId { get; set; }
        public Nullable<int> intBitmapSize { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public Nullable<System.DateTime> dtLastUpdateDate { get; set; }
        public string strBitMapIsfOffline_YN { get; set; }
        public Nullable<System.DateTime> dtImageLastUpdateTimestamp { get; set; }
        public string strBitMapIsfOffline_YN_HD { get; set; }
    }
}
