//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontierVOps.ChannelMapWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFIOSStation
    {
        public string strFIOSServiceId { get; set; }
        public string strStationName { get; set; }
        public string strStationUniqueString { get; set; }
        public string strStationDescription { get; set; }
        public string strStationCallSign { get; set; }
        public string strStationAffiliateId { get; set; }
        public string strCityId { get; set; }
        public string strStateId { get; set; }
        public string strCountyId { get; set; }
        public string strZipCode { get; set; }
        public string strCountryId { get; set; }
        public string strTimeZoneId { get; set; }
        public string strDMAId { get; set; }
        public string strFCCChannelNumber { get; set; }
        public string strStationTypeId { get; set; }
        public int intBitMapId { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public Nullable<System.DateTime> dtLastUpdateDate { get; set; }
        public string strStationOrigin { get; set; }
        public string strDataProviderStationName { get; set; }
        public string strDataProviderStationCallSign { get; set; }
        public string strAbout { get; set; }
        public string strChannelMetadata { get; set; }
        public string strPortalAppID { get; set; }
        public string strProviderAppID { get; set; }
    }
}
