//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontierVOps.ChannelMapWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFIOSLineup
    {
        public string strFIOSRegionId { get; set; }
        public string strFIOSServiceId { get; set; }
        public int intChannelPosition { get; set; }
        public string strLineupDays { get; set; }
        public string strConverterBoxTypeId { get; set; }
        public string strServiceTierId { get; set; }
        public Nullable<System.DateTime> dtLineupEffectiveDate { get; set; }
        public Nullable<System.DateTime> dtLineupExpiryDate { get; set; }
        public System.DateTime dtCreateDate { get; set; }
        public Nullable<System.DateTime> dtLastUpdateDate { get; set; }
        public string strActualFIOSServiceID { get; set; }
        public int iStationGenreID { get; set; }
    }
}
