//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontierVOps.ChannelMapWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFiosBitmapStationMap
    {
        public string strFIOSServiceId { get; set; }
        public int intBitMapId { get; set; }
        public string strFIOSVersionAliasId { get; set; }
        public string dtCreateDate { get; set; }
        public string dtLastUpdateDate { get; set; }
    }
}
